import type { Incident, Inspection, User, Worker } from "@/lib/cscms-types"

export const seedUsers: User[] = [
  {
    id: "USR-ADM-001",
    name: "John Doe",
    email: "admin@cscms.com",
    password: "Admin@123",
    role: "Admin",
    phone: "+1 555-1001",
  },
  {
    id: "USR-INS-001",
    name: "Ravi Kumar",
    email: "inspector@cscms.com",
    password: "Safe@1234",
    role: "Safety Inspector",
    phone: "+1 555-1002",
  },
  {
    id: "USR-WRK-001",
    name: "Field Worker",
    email: "worker@cscms.com",
    password: "Work@1234",
    role: "Worker",
    phone: "+1 555-1003",
  },
  {
    id: "USR-CON-001",
    name: "Contractor Lead",
    email: "contractor@cscms.com",
    password: "Cont@1234",
    role: "Contractor",
    phone: "+1 555-1004",
  },
  {
    id: "USR-AUT-001",
    name: "Gov Authority",
    email: "authority@cscms.com",
    password: "Auth@1234",
    role: "Government Authority",
    phone: "+1 555-1005",
  },
]

export const seedWorkers: Worker[] = [
  {
    id: "WRK-001",
    name: "James Rodriguez",
    role: "Crane Operator",
    contact: "+1 555-0101",
    certStatus: "Valid",
    trainingStatus: "Complete",
    assignedPPE: "Helmet, Harness, Gloves",
    expiryDate: "2026-08-15",
    // Demo mapping: leave unset for most roles.
  },
  {
    id: "WRK-002",
    name: "Sarah Chen",
    role: "Site Supervisor",
    contact: "+1 555-0102",
    certStatus: "Expiring",
    trainingStatus: "Complete",
    assignedPPE: "Helmet, Vest, Boots",
    expiryDate: "2026-03-20",
  },
  {
    id: "WRK-003",
    name: "Mike Thompson",
    role: "Electrician",
    contact: "+1 555-0103",
    certStatus: "Valid",
    trainingStatus: "In Progress",
    assignedPPE: "Helmet, Gloves, Goggles",
    expiryDate: "2026-11-30",
  },
  {
    id: "WRK-004",
    name: "Ana Petrova",
    role: "Safety Inspector",
    contact: "+1 555-0104",
    certStatus: "Expiring",
    trainingStatus: "Overdue",
    assignedPPE: "Helmet, Vest",
    expiryDate: "2026-03-25",
  },
  {
    id: "WRK-005",
    name: "David Kim",
    role: "Welder",
    contact: "+1 555-0105",
    certStatus: "Valid",
    trainingStatus: "Complete",
    assignedPPE: "Helmet, Welding Mask, Gloves",
    expiryDate: "2027-01-15",
  },
  {
    id: "WRK-006",
    name: "Lisa Martinez",
    role: "Plumber",
    contact: "+1 555-0106",
    certStatus: "Expiring",
    trainingStatus: "In Progress",
    assignedPPE: "Helmet, Gloves, Boots",
    expiryDate: "2026-04-10",
  },
  {
    id: "WRK-007",
    name: "Robert Brown",
    role: "Heavy Equipment Op.",
    contact: "+1 555-0107",
    certStatus: "Valid",
    trainingStatus: "Complete",
    assignedPPE: "Helmet, Vest, Harness",
    expiryDate: "2026-09-22",
  },
  {
    id: "WRK-008",
    name: "Emily Watson",
    role: "Scaffolder",
    contact: "+1 555-0108",
    certStatus: "Expired",
    trainingStatus: "Overdue",
    assignedPPE: "None",
    expiryDate: "2025-10-05",
    // Demo mapping: link this worker profile to the seeded worker user.
    userId: "USR-004",
  },
]

export const seedIncidents: Incident[] = [
  {
    id: "INC-2024-042",
    title: "Fall risk near scaffold",
    location: "Building A - Floor 3",
    severity: "High",
    status: "Open",
    description: "Guardrail was not secured in one section.",
    date: "2026-03-01",
    createdByUserId: "USR-INS-001",
  },
  {
    id: "INC-2024-041",
    title: "Minor slip near parking lot",
    location: "Site B - Parking Lot",
    severity: "Medium",
    status: "Under Review",
    description: "Wet surface without warning sign.",
    date: "2026-02-27",
    createdByUserId: "USR-INS-001",
  },
]

export const seedInspections: Inspection[] = [
  {
    id: "INSP-2026-001",
    site: "Site B",
    inspectorName: "Ravi Kumar",
    inspectorEmail: "inspector@cscms.com",
    date: "2026-03-20",
    type: "Electrical Safety",
    status: "Scheduled",
  },
]
